"""empty message

Revision ID: 6a68bbb0de89
Revises: d27a8a5e6b16
Create Date: 2019-12-14 11:59:48.820583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a68bbb0de89'
down_revision = 'd27a8a5e6b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iig')
    op.add_column('sub_topic', sa.Column('request_string1', sa.String(length=200), nullable=False))
    op.add_column('sub_topic', sa.Column('request_string2', sa.String(length=200), nullable=False))
    op.drop_column('sub_topic', 'request_string')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_topic', sa.Column('request_string', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('sub_topic', 'request_string2')
    op.drop_column('sub_topic', 'request_string1')
    op.create_table('iig',
    sa.Column('dates', sa.DATE(), nullable=True),
    sa.Column('months', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bank_categories', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cheque_clearing_micr_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('cheque_clearing_micr_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('cheque_clearing_non_micr_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('cheque_clearing_non_micr_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('electronic_fund_transfers_outward_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('electronic_fund_transfers_outward_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('credit_cards_usage_atms_local_issuing_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('credit_cards_usage_atms_local_issuing_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('credit_cards_usage_atms_abroad_issuing_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('credit_cards_usage_atms_abroad_issuing_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('credit_cards_usage_pos_local_issuing_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('credit_cards_usage_pos_local_issuing_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('credit_cards_usage_pos_abroad_issuing_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('credit_cards_usage_pos_abroad_issuing_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('credit_cards_ecommerce_local_issuing_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('credit_cards_ecommerce_local_issuing_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('credit_cards_ecommerce_abroad_issuing_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('credit_cards_ecommerce_abroad_issuing_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('credit_cards_outstanding_credit', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('debit_cards_usage_atms_local_issuing_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('debit_cards_usage_atms_local_issuing_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('debit_cards_usage_atms_abroad_issuing_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('debit_cards_usage_atms_abroad_issuing_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('debit_cards_usage_pos_local_issuing_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('debit_cards_usage_pos_local_issuing_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('debit_cards_usage_pos_abroad_issuing_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('debit_cards_usage_pos_abroad_issuing_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('debit_cards_ecommerce_local_issuing_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('debit_cards_ecommerce_local_issuing_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('debit_cards_ecommerce_abroad_issuing_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('debit_cards_ecommerce_abroad_issuing_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('prepaid_cards_local_issuing_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('prepaid_cards_local_issuing_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('prepaid_cards_abroad_issuing_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('prepaid_cards_abroad_issuing_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('intl_issued_cards_atm_acquiring_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('intl_issued_cards_atm_acquiring_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('intl_issued_cards_pos_acquiring_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('intl_issued_cards_pos_acquiring_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('intl_issued_cards_ecommerce_acquiring_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('intl_issued_cards_ecommerce_acquiring_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('number_of_cards_net_credit_cards', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('number_of_cards_net_debit_cards', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('number_of_cards_net_prepaid_cards', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('internet_banking_no_banking_customers', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('internet_banking_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('internet_banking_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('mobile_banking_no_banking_agents', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('mobile_banking_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('mobile_banking_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('mobile_banking_no_banking_subscribers', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('agent_banking_no_agents', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('agent_banking_not', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('agent_banking_atc', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('agent_banking_no_banking_subscribers', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('no_atms_in_actual', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    sa.Column('no_of_pos_in_actual', mysql.INTEGER(display_width=30), autoincrement=False, nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
